language: cpp

compiler: g++-9

os: linux
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      packages:
        - g++-9

jobs:
  include:
    - stage: "Build"
      name: "Lox Build"
      script: make lox
    - stage: "UT"
      name: "Unit tests"
      script: make ut
      script: ./ut
